# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false

r:
  - bioc-devel
  - bioc-release

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_PAT
  keep_history: true
  local_dir: docs
  on:
    branch: master
